#!/bin/node

const chalk = require("chalk");
const { calculateOutputFileName, checkAfter, deleteBaseSource, forceSudo, makeBackup, processParams, removePreviousIfNeeded } = require("./utils");

forceSudo();
const config = processParams();

config.out = calculateOutputFileName(config);

removePreviousIfNeeded(config);

makeBackup(config);

if (config.checkAfter)
  checkAfter(config);

if (config.deleteAfter)
  deleteBaseSource(config);

console.log(chalk.green("Done!"));
